# Generated by Django 6.0.6 on 2026-06-21 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle_stage', models.CharField(choices=[('intake', 'Intake'), ('screening', 'Screening'), ('matching', 'Matching'), ('offer', 'Offer'), ('documents', 'Documents'), ('visa', 'Visa'), ('travel', 'Travel'), ('arrival', 'Arrival'), ('post_arrival', 'Post-arrival'), ('re_employment', 'Re-employment')], default='intake', max_length=32)),
                ('source_channel', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web portal'), ('operator', 'Operator (manual)')], max_length=16)),
                ('preferred_language', models.CharField(max_length=8)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('citizenship_iso', models.CharField(max_length=2)),
                ('current_country_iso', models.CharField(max_length=2)),
                ('desired_country_iso', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('duplicate_review_state', models.CharField(choices=[('clear', 'Clear'), ('pending_review', 'Pending review'), ('merged', 'Merged'), ('rejected', 'Rejected as duplicate')], default='clear', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_e164'], name='intake_cand_phone_e_dd7d9e_idx'), models.Index(fields=['telegram_id'], name='intake_cand_telegra_aafaa6_idx'), models.Index(fields=['duplicate_review_state'], name='intake_cand_duplica_643591_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('locale', models.CharField(max_length=8)),
                ('purposes', models.JSONField(default=list)),
                ('lawful_basis', models.CharField(choices=[('consent', 'Consent (GDPR Art. 6(1)(a))'), ('contract', 'Contract (Art. 6(1)(b))'), ('legal_obligation', 'Legal obligation (Art. 6(1)(c))'), ('vital_interests', 'Vital interests (Art. 6(1)(d))'), ('public_task', 'Public task (Art. 6(1)(e))'), ('legitimate_interests', 'Legitimate interests (Art. 6(1)(f))')], default='consent', max_length=32)),
                ('notice_body', models.TextField()),
                ('effective_from', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'locale'), name='uq_consent_version_locale'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('locale',), name='uq_one_active_consent_per_locale')],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web portal'), ('operator', 'Operator (manual)')], max_length=16)),
                ('raw_payload', models.JSONField()),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='intake.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web portal'), ('operator', 'Operator (manual)')], max_length=16)),
                ('locale_shown', models.CharField(max_length=8)),
                ('actor_type', models.CharField(choices=[('candidate', 'Candidate'), ('operator', 'Operator'), ('system', 'System')], max_length=16)),
                ('actor_id', models.CharField(max_length=128)),
                ('evidence', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='intake.candidate')),
                ('consent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='intake.consentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'revoked_at'], name='intake_cons_candida_6dd7dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityMatchReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved_merged', 'Resolved — merged'), ('resolved_distinct', 'Resolved — distinct')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.CharField(blank=True, max_length=128, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_reviews', to='intake.candidate')),
                ('matched_against', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_reviews_against', to='intake.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='intake_iden_state_cfff64_idx')],
            },
        ),
    ]
