# Generated by Django 6.0.6 on 2026-06-22 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateChannelIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('instagram_comment', 'Instagram comment'), ('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('operator', 'Operator (manual)')], max_length=24)),
                ('identifier_type', models.CharField(choices=[('telegram_id', 'Telegram ID'), ('telegram_username', 'Telegram username'), ('phone_e164', 'Phone (E.164)'), ('whatsapp_id', 'WhatsApp ID'), ('instagram_user_id', 'Instagram user ID'), ('instagram_username', 'Instagram username'), ('email', 'Email'), ('website_session', 'Website session')], max_length=32)),
                ('identifier_value', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('self_asserted', 'Self-asserted (unverified)'), ('operator_confirmed', 'Operator confirmed'), ('otp_verified', 'OTP verified'), ('platform_authenticated', 'Platform authenticated')], default='self_asserted', max_length=32)),
                ('source_attribution', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='intake_cand_phone_e_dd7d9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='intake_cand_telegra_aafaa6_idx',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source_channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('instagram_comment', 'Instagram comment'), ('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('operator', 'Operator (manual)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('instagram_comment', 'Instagram comment'), ('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('operator', 'Operator (manual)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('instagram_comment', 'Instagram comment'), ('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('operator', 'Operator (manual)')], max_length=24),
        ),
        migrations.AddField(
            model_name='candidatechannelidentity',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_identities', to='intake.candidate'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_e164',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='telegram_username',
        ),
        migrations.AddIndex(
            model_name='candidatechannelidentity',
            index=models.Index(fields=['identifier_type', 'identifier_value'], name='intake_cand_identif_56e88f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatechannelidentity',
            index=models.Index(fields=['candidate'], name='intake_cand_candida_a4df7e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatechannelidentity',
            index=models.Index(fields=['status'], name='intake_cand_status_ea62f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatechannelidentity',
            constraint=models.UniqueConstraint(fields=('candidate', 'identifier_type', 'identifier_value'), name='uq_candidate_identifier'),
        ),
        migrations.AddConstraint(
            model_name='candidatechannelidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', True), ('status', 'active')), fields=('identifier_type', 'identifier_value'), name='uq_verified_identifier_active'),
        ),
    ]
