# Generated by Django 6.0.6 on 2026-06-21 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(unique=True)),
                ('event_type', models.CharField(choices=[('candidate_created', 'Candidate created'), ('candidate_matched', 'Candidate matched'), ('consent_granted', 'Consent granted'), ('consent_revoked', 'Consent revoked'), ('intake_submitted', 'Intake submitted'), ('identity_review_flagged', 'Identity review flagged')], max_length=48)),
                ('actor_type', models.CharField(max_length=16)),
                ('actor_id', models.CharField(max_length=128)),
                ('subject_type', models.CharField(max_length=48)),
                ('subject_id', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(max_length=32)),
                ('correlation_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='audit_audit_subject_b49148_idx'), models.Index(fields=['correlation_id'], name='audit_audit_correla_563bab_idx'), models.Index(fields=['event_type'], name='audit_audit_event_t_04511c_idx')],
            },
        ),
    ]
