# Generated by Django 6.0.6 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_audit_chain_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('candidate_created', 'Candidate created'), ('candidate_matched', 'Candidate matched'), ('consent_granted', 'Consent granted'), ('consent_revoked', 'Consent revoked'), ('intake_submitted', 'Intake submitted'), ('identity_review_flagged', 'Identity review flagged'), ('channel_identity_added', 'Channel identity added'), ('channel_identity_verified', 'Channel identity verified')], max_length=48),
        ),
    ]
